openapi: 3.0.0
info:
  title: 'Rate api'
  version: 1.0.0
servers:
  -
    url: api
    description: Server
paths:
  /rates:
    post:
      tags:
        - Rates
      description: 'get rates'
      operationId: 03d9dbd02e72a244807f09fa81056d65
      requestBody:
        $ref: '#/components/requestBodies/GetRateRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                properties:
                  data: { $ref: '#/components/schemas/RateResource' }
                type: object
components:
  schemas:
    GetRateRequest:
      required:
        - date
        - currencyCode
      properties:
        date:
          description: date
          type: string
          format: date
          example: '2017-07-21'
        currencyCode:
          description: 'currency code'
          type: string
          format: currency
          example: RUB
        baseCurrencyCode:
          description: 'base currency code'
          type: string
          format: currency
          example: RUB
      type: object
    RateResource:
      properties:
        rate:
          description: rate
          type: number
          format: float
          example: '99.11'
        difference:
          description: difference
          type: number
          format: float
          example: '1.1'
      type: object
  requestBodies:
    GetRateRequest:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GetRateRequest'
